# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-26 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newIdea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('document', models.FileField(blank=True, upload_to='documents/')),
                ('contact', models.CharField(max_length=13)),
            ],
        ),
    ]
