# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-17 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newIdea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_Of_Idea', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('UPI_transaction_ID', models.CharField(max_length=100)),
                ('Your_UPI_ID', models.CharField(max_length=100)),
                ('document', models.FileField(default='ideaFormat/Ideathon_2.0.docx', upload_to='documents/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Contact_Number', models.CharField(max_length=13)),
            ],
        ),
    ]
