# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-03 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it20', '0003_auto_20200127_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='newidea',
            name='UPI',
            field=models.CharField(default='anju.marina.lobo@oksbi', max_length=100),
        ),
    ]
