# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-03 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it20', '0005_auto_20200203_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newidea',
            name='UPI',
            field=models.CharField(max_length=100),
        ),
    ]
