# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-03 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it20', '0006_auto_20200203_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newidea',
            old_name='UPI',
            new_name='UPI_transaction_ID',
        ),
    ]
