# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-17 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it20', '0008_auto_20200205_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='newidea',
            name='Your_UPI_ID',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
