# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-17 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it20', '0009_newidea_your_upi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newidea',
            name='Your_UPI_ID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newidea',
            name='document',
            field=models.FileField(default='ideaFormat/Ideathon_2.0.docx', upload_to='documents/'),
        ),
    ]
